server:
  port: 8282

spring:
  data:
    mongodb:
      uri: mongodb://@documentdb-wqu.cluster-c4eqo06kg56i.us-east-1.docdb.amazonaws.com:27017/?authSource=admin&authMechanism=SCRAM-SHA-1&tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: tax
javax:
  net:
    ssl:
      trustStore: /tmp/certs/rds-truststore.jks
      trustStorePassword: skillstorm