server:
  port:

spring:
  data:
    mongodb:
<<<<<<< Updated upstream
      uri: mongodb+srv://skillstormproject2group2:MuchStrongerPassword123@skillstorm-project2-gro.vswf1wk.mongodb.net/
      database: project2
       

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true


=======
      uri:
      database:
>>>>>>> Stashed changes
